# Generated by Django 4.0.4 on 2022-05-21 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('food_description', models.CharField(blank=True, max_length=2000)),
                ('food_price', models.FloatField()),
                ('food_image', models.ImageField(default='default.png', upload_to='images/')),
                ('food_types', models.CharField(choices=[('hlavné jedlo', 'hlavné jedlo'), ('špecialita', 'špecialita'), ('burger', 'burger'), ('príloha', 'príloha'), ('cestoviny', 'cestoviny'), ('šalát', 'šalát'), ('pizza', 'pizza'), ('polievka', 'polievka'), ('dezert', 'dezert'), ('nápoj', 'nápoj')], max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
