# Generated by Django 4.0.4 on 2022-05-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='food_types',
            field=models.CharField(choices=[('hlavné jedlo', 'hlavné jedlo'), ('špecialita', 'špecialita'), ('burger', 'burger'), ('príloha', 'príloha'), ('cestoviny', 'cestoviny'), ('šalát', 'šalát'), ('pizza', 'pizza'), ('polievka', 'polievka'), ('dezert', 'dezert'), ('nápoj', 'nápoj')], default='špecialita', max_length=20),
        ),
    ]
